version: '3.8'

services:
  identity-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: identity-service
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      # Add other environment variables as needed
    restart: unless-stopped
    networks:
      - clavehr_network

networks:
  clavehr_network:
    driver: bridge